build : main structures room creep mining
	g++ -o build main.o structures.o room.o creep.o mining.o

main : main.cpp
	g++ -c main.cpp

structures : structures.cpp
	g++ -c structures.cpp

room : room.cpp
	g++ -c room.cpp

creep : creep.cpp
	g++ -c creep.cpp

mining:
	g++ -c mining.cpp