build : main structures room creep mining
	g++ -o build main.o structures.o room.o creep.o mining.o

main : main.cpp
	g++ -c main.cpp

structures : structures.h structures.cpp
	g++ -c structures.cpp

room : room.h room.cpp
	g++ -c room.cpp

creep : creep.h creep.cpp
	g++ -c creep.cpp

mining : mining.cpp
	g++ -c mining.cpp